#!/bin/sh
set -eu
umask 077
cd /opt/lifewithlabr/current
runuser -u lifewithlabr -- env CMS_DATA_DIR=/var/lib/lifewithlabr /opt/lifewithlabr/runtime/bin/node cms/backup.mjs
install -d -m 700 /var/backups/lifewithlabr
stamp=$(date -u +%F)
tar -czf "/var/backups/lifewithlabr/site-$stamp.tar.gz" -C /var/lib/lifewithlabr "backups/content-$stamp.sqlite" uploads
# Retain only backups generated by this script; media and live data are never removed.
find /var/backups/lifewithlabr -maxdepth 1 -type f -name 'site-????-??-??.tar.gz' -mtime +14 -delete
